name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 11.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
    dependencies:
      - framework: Frameworks/BoringSSL.framework
      - framework: Frameworks/CgRPC.framework
      - framework: Frameworks/Realm.framework
      - framework: Frameworks/RealmSwift.framework
      - framework: Frameworks/SLProtofiles.framework
      - framework: Frameworks/StreamLayer.framework
      - framework: Frameworks/StreamLayerVendor.framework
      - framework: Frameworks/SwiftGRPC.framework
      - framework: Frameworks/SwiftProtobuf.framework
      - framework: Frameworks/WebRTC.framework
