name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 11.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
    dependencies:
      - carthage: StreamLayer
      - carthage: StreamLayerVendor
      - carthage: WebRTC
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: SLProtofiles
      - carthage: SwiftGRPC
      - carthage: CgRPC
      - carthage: BoringSSL
      - carthage: SwiftProtobuf
      - carthage: SnapKit # sample implementation only
      - carthage: RxSwift # sample implementation only
      - carthage: RxRelay # sample implementation only
      - carthage: RxCocoa # sample implementation only
