name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 12.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
        ENABLE_BITCODE: NO
    dependencies:
      - carthage: StreamLayer
      - carthage: StreamLayerVendor
      - carthage: VoxImplant
      - carthage: WebRTC
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: SLProtofiles
      - carthage: Logging
      - carthage: NIO
      - carthage: NIOConcurrencyHelpers
      - carthage: NIOFoundationCompat
      - carthage: NIOHPACK
      - carthage: NIOHTTP1
      - carthage: NIOHTTP2
      - carthage: NIOSSL
      - carthage: NIOTLS
      - carthage: NIOTransportServices
      - carthage: SwiftProtobuf
      - carthage: NIOExtras
      - carthage: SwiftGRPC
      - carthage: CGRPCZlib
      - carthage: CNIOAtomics
      - carthage: CNIOBoringSSL
      - carthage: CNIOBoringSSLShims
      - carthage: CNIODarwin
      - carthage: CNIOWindows
      - carthage: CNIOHTTPParser
      - carthage: CNIOLinux
      - carthage: Lottie
      - carthage: SwiftDraw
      - carthage: Branch
