name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 11.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
        ENABLE_BITCODE: NO
    dependencies:
      - carthage: StreamLayer
      - carthage: StreamLayerVendor
      - carthage: WebRTC
      - carthage: Realm
      - carthage: RealmSwift
      - carthage: SLProtofiles
      - carthage: SwiftProtobuf
      - carthage: VoxImplant
      - carthage: GRPC
      - carthage: Logging
      - carthage: NIO
      - carthage: NIOConcurrencyHelpers
      - carthage: NIOFoundationCompat
      - carthage: NIOHPACK
      - carthage: NIOHTTP1
      - carthage: NIOHTTP2
      - carthage: NIOSSL
      - carthage: NIOTLS
      - carthage: NIOTransportServices
      - carthage: SwiftProtobuf
      - carthage: CGRPCZlib
      - carthage: CNIOAtomics
      - carthage: CNIOBoringSSL
      - carthage: CNIOBoringSSLShims
      - carthage: CNIODarwin
      - carthage: CNIOHTTPParser
      - carthage: CNIOLinux
      - carthage: CNIOSHA1
      - carthage: SnapKit # sample implementation only
      - carthage: RxSwift # sample implementation only
      - carthage: RxRelay # sample implementation only
      - carthage: RxCocoa # sample implementation only

      - carthage: Action
      - carthage: RxDataSources
      - carthage: Differentiator
