name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.demo-games
        ENABLE_BITCODE: NO
    dependencies:
      - package: StreamLayer
      - package: SnapKit
      - package: RxSwift
packages:
  StreamLayer:
    url: https://github.com/StreamLayer/sdk-ios.git
    minorVersion: 8.14.12
  SnapKit:
    github: SnapKit/SnapKit
    from: 5.0.0
  RxSwift:
    github: ReactiveX/RxSwift
    from: 6.0.0
