name: SwiftDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 15.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
        ENABLE_BITCODE: NO
    dependencies:
      - package: StreamLayer
packages:
  StreamLayer:
    url: https://github.com/StreamLayer/sdk-ios.git
    minorVersion: 8.14.16
