name: ObjCDemo

include:
  - project.base.yml

targets:
  Demo:
    platform: iOS
    deploymentTarget:
      iOS: 11.0
    type: application
    sources:
      - path: Source
    requiresObjCLinking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.streamlayer.swift-demo
    dependencies:
      - carthage: StreamLayer
      - carthage: StreamLayerVendor
      - carthage: WebRTC
